//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerSubscription.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerInfo
    {
        public string CustomerName { get; set; }
        public string CustomerType { get; set; }
        public System.DateTime SubFrom { get; set; }
        public System.DateTime SubTo { get; set; }
    }
}
